### ISSUE TITLE
Type mismatch: inferred type is MainActivity but FlutterEngine was expected

### ISSUE THREAD

**Issue by ihsanalgul** [divyanshub024/chitr#11]
Hi, I read your article from [medium.com](https://medium.com/flutter-community/creating-a-wallpaper-app-in-flutter-part-2-d28895320ce0) thanks for your sharing, I have learn many things. I have an error,  could you help me? 

Under the android folder /MainActivity.kt Kotlin file throws an error.

I tried these below:

flutter clean
flutter pub cache repair
I read about other type mismatch error questions from here but unfortunately not found anything.

Any help appriciated. My code is as below.

```
    package com.combasis.wallpaper_son_app
import android.os.Bundle
import io.flutter.app.FlutterActivity
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugins.GeneratedPluginRegistrant
import java.io.IOException
import android.app.WallpaperManager
import android.graphics.BitmapFactory
import java.io.File
import android.os.Build
import android.annotation.TargetApi
import android.content.Context
import io.flutter.Log

private const val CHANNEL = "com.combasis.wallpaper_son_app"
class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        GeneratedPluginRegistrant.registerWith(this)

    MethodChannel(flutterView, CHANNEL).setMethodCallHandler { call, result ->
        if (call.method == "setWallpaper") {
            val arguments = call.arguments as ArrayList<*>
            val setWallpaper = setWallpaper(arguments[0] as String, applicationContext, arguments[1] as Int)

            if (setWallpaper == 0) {
                result.success(setWallpaper)
            } else {
                result.error("UNAVAILABLE", "", null)
            }
        } else {
            result.notImplemented()
        }
    }
}
```

**Comment by varadgauthankar** [comment]
Hello, did you found the solution? as I am also facing the same issue.

Thanks

**Comment by utsav2727** [comment]
I have the same problem, can anyone help please?

**Comment by utsav2727** [comment]
If any got the solution please help

**Comment by utsav2727** [comment]
> Hello, did you found the solution? as I am also facing the same issue.
> 
> Thanks



> Hi, I read your article from [medium.com](https://medium.com/flutter-community/creating-a-wallpaper-app-in-flutter-part-2-d28895320ce0) thanks for your sharing, I have learn many things. I have an error, could you help me?
> 
> Under the android folder /MainActivity.kt Kotlin file throws an error.
> 
> I tried these below:
> 
> flutter clean
> flutter pub cache repair
> I read about other type mismatch error questions from here but unfortunately not found anything.
> 
> Any help appriciated. My code is as below.
> 
> ```
>     package com.combasis.wallpaper_son_app
> import android.os.Bundle
> import io.flutter.app.FlutterActivity
> import io.flutter.plugin.common.MethodChannel
> import io.flutter.plugins.GeneratedPluginRegistrant
> import java.io.IOException
> import android.app.WallpaperManager
> import android.graphics.BitmapFactory
> import java.io.File
> import android.os.Build
> import android.annotation.TargetApi
> import android.content.Context
> import io.flutter.Log
> 
> private const val CHANNEL = "com.combasis.wallpaper_son_app"
> class MainActivity: FlutterActivity() {
>     override fun onCreate(savedInstanceState: Bundle?) {
>         super.onCreate(savedInstanceState)
>         GeneratedPluginRegistrant.registerWith(this)
> 
>     MethodChannel(flutterView, CHANNEL).setMethodCallHandler { call, result ->
>         if (call.method == "setWallpaper") {
>             val arguments = call.arguments as ArrayList<*>
>             val setWallpaper = setWallpaper(arguments[0] as String, applicationContext, arguments[1] as Int)
> 
>             if (setWallpaper == 0) {
>                 result.success(setWallpaper)
>             } else {
>                 result.error("UNAVAILABLE", "", null)
>             }
>         } else {
>             result.notImplemented()
>         }
>     }
> }
> ```

Did you found solution?

**Comment by ihsanalgul** [comment]
Please remove GeneratedPluginRegistrant.registerWith(flutterEngine); from MainActivity.kt and update as follows.

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}


According to the stack: [https://stackoverflow.com/questions/63349813/type-mismatch-inferred-type-is-mainactivity-but-flutterengine-was-expected](https://stackoverflow.com/questions)
