### ISSUE TITLE
App Crashes on applying a wallpaper.

### ISSUE THREAD

**Issue by bimsina** [divyanshub024/chitr#6]
The app crashes when I try to apply an image as wallpaper with the error :
```
E/flutter (18158): 	at com.divyanshu.chitr.MainActivity.access$setWallpaper(MainActivity.kt:18)
E/flutter (18158): 	at com.divyanshu.chitr.MainActivity$onCreate$1.onMethodCall(MainActivity.kt:27)
E/flutter (18158): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/flutter (18158): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/flutter (18158): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/flutter (18158): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (18158): 	at android.os.MessageQueue.next(MessageQueue.java:328)
E/flutter (18158): 	at android.os.Looper.loop(Looper.java:164)
E/flutter (18158): 	at android.app.ActivityThread.main(ActivityThread.java:5737)
E/flutter (18158): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (18158): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/flutter (18158): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
E/flutter (18158):
F/flutter (18158): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
```
This issue doesnt appear if I change `wm?.setBitmap(bitmap, null, true, wallpaperType)` to `wm?.setBitmap(bitmap)` but that way I can only set the home screen wallpaper.

**Comment by NaseerUllahAwan** [comment]
I have also the same issue can anyone tell me why this occure?

**Comment by NaseerUllahAwan** [comment]
This does not work on a lower level of android devices. but work fine on the newest android devices.

**Comment by NaseerUllahAwan** [comment]
This wallpaper app crashes by applying wallpaper on lower android versions(4.4.4). And working fine on higher android versions like ( android version 9).

**Comment by NaseerUllahAwan** [comment]
> The app crashes when I try to apply an image as wallpaper with the error :
> 
> ```
> E/flutter (18158): 	at com.divyanshu.chitr.MainActivity.access$setWallpaper(MainActivity.kt:18)
> E/flutter (18158): 	at com.divyanshu.chitr.MainActivity$onCreate$1.onMethodCall(MainActivity.kt:27)
> E/flutter (18158): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
> E/flutter (18158): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
> E/flutter (18158): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
> E/flutter (18158): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> E/flutter (18158): 	at android.os.MessageQueue.next(MessageQueue.java:328)
> E/flutter (18158): 	at android.os.Looper.loop(Looper.java:164)
> E/flutter (18158): 	at android.app.ActivityThread.main(ActivityThread.java:5737)
> E/flutter (18158): 	at java.lang.reflect.Method.invoke(Native Method)
> E/flutter (18158): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
> E/flutter (18158): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
> E/flutter (18158):
> F/flutter (18158): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
> ```
> 
> This issue doesnt appear if I change `wm?.setBitmap(bitmap, null, true, wallpaperType)` to `wm?.setBitmap(bitmap)` but that way I can only set the home screen wallpaper.

Did you find any solution...

**Comment by bimsina** [comment]
@NaseerUllahAwan I used it to set the home screen wallpaper only and it works fine for that.
